name: broadcastreceiverapp
description: A new Flutter project

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

# The environment specifies the Dart SDK version your project is compatible with.
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.15
  provider: ^5.0.0
  google_fonts: ^6.2.1
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  connectivity_plus: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
